name: "colorama"
on: [push]
jobs:
  colorama:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ ubuntu, windows ]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/checkout@v1
    - run: |
        python -m pip install -U --user pip --progress-bar off
        python -m pip install -U --user colorama --progress-bar off

    - run: python -c "import colorama; colorama.init(); print(colorama.Fore.RED + 'hello' + colorama.Fore.RESET)"
    - run: python -c "import colorama; colorama.init(); print(colorama.Fore.RED + 'hello' + colorama.Fore.RESET)"
      env:
        FORCE_COLOR: 1
    - run: python -c "import colorama; colorama.init(); print(colorama.Fore.RED + 'hello' + colorama.Fore.RESET)"
      env:
        PY_COLORS: 1
    - run: python -c "import colorama; colorama.init(); print(colorama.Fore.RED + 'hello' + colorama.Fore.RESET)"
      env:
        PYCHARM_HOSTED: 1
    - run: python -c "import colorama; colorama.init(); print(colorama.Fore.RED + 'hello' + colorama.Fore.RESET)"
      env:
        PYCHARM_HOSTED: 1
        PY_COLORS: 1

  cmd:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/checkout@v1
    - shell: cmd
      run: |
        python -m pip install -U --user pip --progress-bar off
        python -m pip install -U --user colorama --progress-bar off

    - shell: cmd
      run: python -c "import colorama; colorama.init(); print(colorama.Fore.RED + 'hello' + colorama.Fore.RESET)"
    - shell: cmd
      run: python -c "import colorama; colorama.init(); print(colorama.Fore.RED + 'hello' + colorama.Fore.RESET)"
      env:
        FORCE_COLOR: 1
    - shell: cmd
      run: python -c "import colorama; colorama.init(); print(colorama.Fore.RED + 'hello' + colorama.Fore.RESET)"
      env:
        PY_COLORS: 1
    - shell: cmd
      run: python -c "import colorama; colorama.init(); print(colorama.Fore.RED + 'hello' + colorama.Fore.RESET)"
      env:
        PYCHARM_HOSTED: 1
    - shell: cmd
      run: python -c "import colorama; colorama.init(); print(colorama.Fore.RED + 'hello' + colorama.Fore.RESET)"
      env:
        PYCHARM_HOSTED: 1
        PY_COLORS: 1

  bash:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/checkout@v1
    - shell: bash
      run: |
        python -m pip install -U --user pip --progress-bar off
        python -m pip install -U --user colorama --progress-bar off

    - shell: bash
      run: python -c "import colorama; colorama.init(); print(colorama.Fore.RED + 'hello' + colorama.Fore.RESET)"
    - shell: bash
      run: python -c "import colorama; colorama.init(); print(colorama.Fore.RED + 'hello' + colorama.Fore.RESET)"
      env:
        FORCE_COLOR: 1
    - shell: bash
      run: python -c "import colorama; colorama.init(); print(colorama.Fore.RED + 'hello' + colorama.Fore.RESET)"
      env:
        PY_COLORS: 1
    - shell: bash
      run: python -c "import colorama; colorama.init(); print(colorama.Fore.RED + 'hello' + colorama.Fore.RESET)"
      env:
        PYCHARM_HOSTED: 1
    - shell: bash
      run: python -c "import colorama; colorama.init(); print(colorama.Fore.RED + 'hello' + colorama.Fore.RESET)"
      env:
        PYCHARM_HOSTED: 1
        PY_COLORS: 1
