name: "push"
on: [push]
jobs:
  multiple:
    runs-on: ubuntu-latest
    steps:
    - run: sudo dpkg --add-architecture i386
    - run: sudo apt-get update -q

  single:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -q

  custom:
    runs-on: ubuntu-latest
    steps:
    - shell: bash --noprofile --norc -eo pipefail {0}
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -q

  sudo:
    runs-on: ubuntu-latest
    steps:
    - shell: sudo bash --noprofile --norc -eo pipefail {0}
      run: |
        dpkg --add-architecture i386
        apt-get update -q
